newnewproject:
  outputs:
    dev:
      account: UTZEHJC-GC88982
      database: MOVIELENS
      password: dbtPassword123
      role: TRANSFORM
      schema: dev
      threads: 1
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
  target: dev
zomato:
  outputs:
    dev:
      account: RWFKIZM-MR24347
      database: ZOMATO
      password: Akhil@12042005
      role: DBT_ROLE
      schema: STAGING
      threads: 8
      type: snowflake
      user: AKHLIBAKI
      warehouse: ZOMATO_WH
  target: dev
